### PR TITLE
Proxies

### PR DESCRIPTION
**Pull request by hazraa**
Our use case is a strict outgoing firewall policy. 
With the many login.microsoftonline.com IPs, a proxy makes sense. 
We use django-microsoft-auth for staff admin login of our django app which also consumes many
external API's and not everything goes via a proxy, so we don't want a blanket proxy
config via the app environment like "http_proxy" etc. So passing a proxy down into
requests.Sessions solves our use case. Didn't see this option available yet.

### CODE REVIEW

**Comment by AngellusMortis** [comment]
I finally got GHA set up and working. Please sync with master and then fix any CI issues if you would like me to continue with merging the PR.

**Comment by AngellusMortis** [comment]
If you revert your changes to `ci.yml` and sync with master again, it should run everything correctly now. Sorry, first time I have really dealt with GHA with OSS forks. It is rather a PITA.

**Comment by hazraa** [comment]
yeh, just trying to clear CI errors on my local "proxies" branch with 
that tmp change.
Did add a local CodeClimate CC_TEST_REPORTER_ID in the env, I see its 
hardwired now.

black maybe complaing about:
tests/test_client.py: Python script, ASCII text executable, with CRLF 
line terminators
Other py files seems to 'normal' eg:
   microsoft_auth/urls.py: Python script, ASCII text executable

harry

**Comment by AngellusMortis** [comment]
For black/formatting, you should just need to make sure you have the dev reqs installed (`pip install -r reqs/dev requirements.txt`) then run `.bin/format-code`. Or just `black .` from the git repo root.

You can ignore the 1 CC linting error. I can refractor that later.

**Pull request merged**
