### PR TITLE
- Additional Parameters in URL authentication code retrieval

### PR DESCRIPTION
**Pull request by TheCyberFox**
- Added the ability to include additional parameters in Microsoft authentication code retrieval url creation.
The additional parameters you can include are listed within this link https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

### CODE REVIEW

**Comment by AngellusMortis** [comment]
Please add tests and docs. You can ignore the CC error.

**Comment by TheCyberFox** [comment]
The methods you have for contributing and testing the code seem to be outdated. I used what methods I could and they passed but feel free to double check. As far as the check that fails above according to codeclimate, the only way I could think to shorten it would be to condense the dictionary defining the configuration settings.

**Comment by TheCyberFox** [comment]
I have no idea what happened with the test_client.py file for it to register like it did. I only added a new feature to the _get_auth_url() method as well as added a test method at the very bottom of the file.

**Comment by AngellusMortis** [comment]
CI is failing. And yeah, it looks like the docs are out of date on how to test. You can use the CI workflow as a reference:

https://github.com/AngellusMortis/django_microsoft_auth/blob/master/.github/workflows/ci.yml#L42-L52

**Comment by TheCyberFox** [comment]
Okay, I got 9/10 of the CI tests in the workflow passing on my side. The last CI test seems to be based on format. The errors I am presented with are very minor and I am not quite sure there is a better way of declaring method parameters; if there is I would love to know.

**Comment by AngellusMortis** [comment]
Just have some linting issues left.

https://github.com/AngellusMortis/django_microsoft_auth/runs/7414490199?check_suite_focus=true#step:5:19

Need to run black and fix the line lengths (if they are still too long).

**Comment by TheCyberFox** [comment]
Okay, the only check not passing is the CC error about the configuration file which you said I could ignore.

**Pull request merged**
