### PR TITLE
Fixed overwriting changes to UserAdmin

### PR DESCRIPTION
**Pull request by pandafy**
Instead of defining a new UserAdmin class to add inline forms, monkey patch existing UserAdmin.

This prevents overwriting changes made to UserAdmin by other Django apps.

### CODE REVIEW

**Comment by pandafy** [comment]
Hey @AngellusMortis! Can we move ahead with this PR?

**Comment by pandafy** [comment]
@AngellusMortis ping!

**Comment by AngellusMortis** [comment]
Your PR was accessing a private method from a Django function. Meaning it could break any time. If you want your own user admin, you can easily do the same thing this app does. Load your app after this one, unregister the existing admin and register your own.

**Comment by AngellusMortis** [comment]
Otherwise, you can find another solution that does not require using Django internals and not pinging me. It is rude.

**Pull request closed without merging**
