### PR TITLE
Support specifying Tenant, Scope, and storing Token

### PR DESCRIPTION
**Pull request by aviv-ebates**
This only supports the `ma` auth mode, but it basically allows making API calls to Microsoft on behalf of users.

### CODE REVIEW

**Comment by AngellusMortis** [comment]
I do not want to store tokens in the database for this app. That allows Django admins to go in, retrieve tokens and make calls as any user that has sign into the application. 

I would not be opposed to the token getting stored in a cookie value so it on the user's side whether the server gets the token and they can choose to revoke it at any time. `microsoft_auth.backends.MicrosoftAuthenticationBackend` could easily token any tokens it gets from Microsoft/Xbox in a cookie value and then you could create a helper method that would take a request, read the cookies and give you a Microsoft client.

**Comment by aviv-ebates** [comment]
I have no use-case to store token in cookies, so I'm just going to drop that.
If you already picked up the tenant change, then I guess all that's left here is the Scope selection, which also doesn't makes sense w/o storing the token, so there's nothing in here to keep.

**Comment by AngellusMortis** [comment]
> I have no use-case to store token in cookies, so I'm just going to drop that.

What is the use case you have for reusing the tokens after log in? If I understand that, there might be another solution.

**Comment by aviv-ebates** [comment]
My app uses the token to make calls on behalf of the user while the user is away (attaching rooms to meetings, actually).

I'll think about a hook at some point in the future, for now I don't really have the time to work on this.

**Pull request closed without merging**
