### PR TITLE
Ignore case in email address when doing user lookup

### PR DESCRIPTION
**Pull request by JordanReiter**
This addresses issue #301, and includes a test case.

### CODE REVIEW

**Comment by AngellusMortis** [comment]
`i_exact` is _very_ bad for performance as it does not use the index on the column if it has one. You should instead do a data migration to force all of your emails to lower case. Feel free to then make a PR to lower case the email before storing it into the database here.

**Comment by JordanReiter** [comment]
The real problem is that email addresses are added by users and
capitalization may not be consistent. So in addition to a migration,
anytime a user record is saved and the email is not lower case, it needs to
be stored as lower case. I can make a PR for that instead.

**Comment by obi-jerome** [comment]
I think the best solution would be to enable the developer to choose his own user resolver function.
Like it is done in OpenID Connect authentication for Django Rest Framework
with the OIDC_RESOLVE_USER_FUNCTION Parameter.
https://github.com/ByteInternet/drf-oidc-auth

In Django, the email field is not unique, this means two users can have the same email sometimes.
It would be great if each developer could choose how the User Lockup is done.

**Comment by AngellusMortis** [comment]
keep conversation related to the original issue on the issue itself, not the PR. No one will see discussion on the PR.

**Pull request closed without merging**
