### PR TITLE
Handle names in LastName, FirstName format

### PR DESCRIPTION
**Pull request by JordanReiter**

### CODE REVIEW

**Comment by AngellusMortis** [comment]
Closing in favor of #351

**Comment by JordanReiter** [comment]
OK, this does not actually solve the problem. All of my users will still be stored as:

First name: "Lastname,"
Last name: "Firstname"

Fortunately for me, this does not matter, as users never see the first name and last name, so it will just have to always be wrong for them and for other people using this library whose system uses the "Lastname, Firstname" format.

**Comment by AngellusMortis** [comment]
My mistake, you are right, this is a different use case. If you want to update the PR to resolve the conflicts, I can go a head and merge it.

**Comment by JordanReiter** [comment]
Hi, sorry I missed this. I've updated the PR to resolve the conflicts.

**Pull request merged**
